# Generated by Django 5.2.6 on 2025-09-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_orders_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=23, max_digits=8, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('in proccess', 'In proccess'), ('canceled', 'Canceled'), ('finished', 'Finished'), ('pending', 'Pending')]),
        ),
    ]
